-- Customers and their per-currency accounts.
--
-- Identifiers are UUIDs generated by the application: the API never exposes
-- a sequence number, which would reveal how many customers exist.

CREATE TABLE customers (
    id         UUID        PRIMARY KEY,
    name       TEXT        NOT NULL CHECK (length(trim(name)) > 0),
    created_at TIMESTAMPTZ NOT NULL
);

-- One row per customer per currency, plus the system accounts the ledger
-- adds later (fees, FX position, funding), which belong to no customer.
CREATE TABLE accounts (
    id          UUID        PRIMARY KEY,
    customer_id UUID        REFERENCES customers (id),
    currency    CHAR(3)     NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    type        TEXT        NOT NULL CHECK (type IN ('CUSTOMER', 'FEE_REVENUE', 'FX_POSITION', 'FUNDING')),
    -- In the currency's minor unit. A cache of the account's postings, kept
    -- in step with them in the same transaction.
    balance     BIGINT      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL,

    -- A customer account has a customer; a system account has none.
    CONSTRAINT owner_matches_type CHECK ((type = 'CUSTOMER') = (customer_id IS NOT NULL)),
    -- The application checks this before writing; the database refuses it
    -- anyway, so a bug in that check cannot overdraw an account.
    CONSTRAINT customer_balance_not_negative CHECK (type <> 'CUSTOMER' OR balance >= 0)
);

-- A customer has at most one account per currency.
CREATE UNIQUE INDEX accounts_one_per_customer_currency
    ON accounts (customer_id, currency) WHERE type = 'CUSTOMER';
